name: update-activity

on:
  schedule:
    - cron: '0 0 * * 3'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: jamesgeorge007/github-activity-readme@v0.3.6
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          COMMIT_MSG: Updated recente github moves
          MAX_LINES: 5
